namespace BattleNetShop.Data.SQLite
{
    using System;
    using System.Collections.Generic;

    public class SQLiteHandler
    {
        // Tuple<string, ICollection<Tuple<string, decimal>> will become a class
        // Task 6 input
        public ICollection<Tuple<string, decimal>> ReadProductTaxes()
        {
            throw new NotImplementedException();
        }

        // Since you need to read some reports, they have to be generated first.
        // Data can be generated by private class or by hand or however you decide. Best way is to use the 
        // library required by the teamwork specification
        public void SeedData()
        {
            throw new NotImplementedException();
        }

        private object CreateConnection()
        {
            return null;
        }
    }
}
