//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleNetShop.Data.SQLite {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class SQLiteDBSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQLiteDBSettings defaultInstance = ((SQLiteDBSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQLiteDBSettings())));
        
        public static SQLiteDBSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\BattleNetShop.Data.SQLite\\SampleData\\Products.txt")]
        public string SQLiteDBSampleDataProducts {
            get {
                return ((string)(this["SQLiteDBSampleDataProducts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\User\\Documents\\")]
        public string SQLiteDBFileLocation {
            get {
                return ((string)(this["SQLiteDBFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleNetShop.sqlite")]
        public string SQLiteDBName {
            get {
                return ((string)(this["SQLiteDBName"]));
            }
        }
    }
}
