//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleNetShop.Data.SqLite {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SqLiteDbSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SqLiteDbSettings defaultInstance = ((SqLiteDbSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SqLiteDbSettings())));
        
        public static SqLiteDbSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\InitialData\\InitialData.xlsx")]
        public string SQLiteDBSampleDataProducts {
            get {
                return ((string)(this["SQLiteDBSampleDataProducts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\InitialData\\SQLiteDB\\BattleNetShop.sqlite")]
        public string SQLiteDBLocation {
            get {
                return ((string)(this["SQLiteDBLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Version=3;")]
        public string SQLiteConnectionString {
            get {
                return ((string)(this["SQLiteConnectionString"]));
            }
            set {
                this["SQLiteConnectionString"] = value;
            }
        }
    }
}
