namespace BattleNetShop.Data.MySql
{
    using System;
    using System.Collections.Generic;

    public class MySqlHandler
    {
        // ICollection<Tuple<int, string, string, int, decimal>> will become a class
        // Task 6 input
        public ICollection<Tuple<int, string, string, int, decimal>> ReadAllReports()
        {
            throw new NotImplementedException();
        }

        // Tuple<string, ICollection<Tuple<int, string, string, int, decimal>> will become a class
        // Task 4 output
        public void SaveAllReports(ICollection<Tuple<int, string, string, int, decimal>> allReports)
        {
            throw new NotImplementedException();
        }

        // Since you need to read some reports, they have to be generated first.
        // Data can be generated by private class or by hand or however you decide. Best way is to use the 
        // library required by the teamwork specification
        public void SeedData()
        {
            throw new NotImplementedException();
        }

        private object CreateConnection()
        {
            return null;
        }
    }
}
