namespace BattleNetShop.Data.Xml
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Use this class to do the low level reading / writing to files (if you want)
    /// </summary>
    public class XmlHandler
    {
        // Since you need to read some reports, they have to be generated first.
        // Data can be generated by private class or by hand or however you decide. Best way is to use the 
        // library required by the teamwork specification
        public void SeedData()
        {
            throw new NotImplementedException();
        }
    }
}
