namespace BattleNetShop.Data.Xml
{
    using System;
    using System.Collections.Generic;

    public class XMLHandler
    {
        // Tuple<string, ICollection<Tuple<DateTime, decimal>>> will become a class
        // Task 5 input
        public ICollection<Tuple<string, ICollection<Tuple<DateTime, decimal>>>> ReadAllExpensesByMonth(string filePath)
        {
            throw new NotImplementedException();
        }

        // Tuple<string, ICollection<Tuple<DateTime, decimal>>> will become a class
        // Task 3 output
        public void GenerateReport(ICollection<Tuple<string, ICollection<Tuple<DateTime, decimal>>>> allSales, string filePath)
        {
            throw new NotImplementedException();
        }

        // Since you need to read some reports, they have to be generated first.
        // Data can be generated by private class or by hand or however you decide. Best way is to use the 
        // library required by the teamwork specification
        public void SeedData()
        {
            throw new NotImplementedException();
        }
    }
}
