#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BattleNetShop.Data.MySqlTelerikDA;

namespace BattleNetShop.Data.MySqlTelerikDA	
{
	public partial class MySqlSaleReportEntities : OpenAccessContext, IMySqlSaleReportEntitiesUnitOfWork
	{
		private static string connectionStringName = @"MySqlConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public MySqlSaleReportEntities()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public MySqlSaleReportEntities(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public MySqlSaleReportEntities(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public MySqlSaleReportEntities(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public MySqlSaleReportEntities(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Salereport> Salereports 
		{
			get
			{
				return this.GetAll<Salereport>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of MySqlSaleReportEntities.
		/// </summary>
		/// <param name="config">The BackendConfiguration of MySqlSaleReportEntities.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IMySqlSaleReportEntitiesUnitOfWork : IUnitOfWork
	{
		IQueryable<Salereport> Salereports
		{
			get;
		}
	}
}
#pragma warning restore 1591
